### ISSUE TITLE
what input size is

### ISSUE THREAD

**Issue by YuYangmio** [upskyy/ContextNet#5]
I would like to ask what input size can be understood as a voice signal

**Comment by upskyy** [comment]
Extract the feature from audio signal and have a shape of the form (batch, seq_len, dim). In the code, dim is set to 80 by default.

**Comment by YuYangmio** [comment]
thanks

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
idcetim, @loveysuby, @bacemtayeb, @mcpeixoto, @argosopentech, @canesin, @X-rayLaser, @lu-m13, @sarthak0714, @Bakar31, @AsakusaRinne, @pbadeer, @YyMurphy, @shivamnegi92, @hamidaskarov, @xTayEx, @ganzobtn, @motanzg, @Serega164, @moskomule

**Comment by pbadeer** [comment]
> 
> Hello,
> 
> We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!
> 
> As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:
> 
> - Health insurance coverage
> - Retirement savings plan
> - Flexible work schedule
> - Generous vacation and paid time off
> - Professional development opportunities
> 
> To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.
> 
> Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.
> 
> **Important:** You have 24 hours to complete the application process.
> 
> If you have any questions or need further information, please don't hesitate to contact us.
> 
> Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.
> 
> Best regards,  
> GitHub Recruitment Team
> idcetim, @loveysuby, @bacemtayeb, @mcpeixoto, @argosopentech, @canesin, @X-rayLaser, @lu-m13, @sarthak0714, @Bakar31, @AsakusaRinne, @pbadeer, @YyMurphy, @shivamnegi92, @hamidaskarov, @xTayEx, @ganzobtn, @motanzg, @Serega164, @moskomule

This is a phishing attempt, do not open the link! The post has been reported.

**Comment by rarents1975** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
wilbeibi, @eruma, @i6173215, @monatis, @real-panda2, @lucencywe, @apatella, @westoque, @KefanC, @Northrend, @arhartley, @ae86208, @liulu112601, @JL-Cheng, @Haotian-Zhang, @MrBenzWorld, @vishyfortheworld, @abhinand5, @LeeJodie, @redaharisyahiaoui
